name: Deploy jackson-dataformat-xlsx-lite
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      - name: setup java
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde
        with:
          java-version: '8'
          java-package: jdk
          server-id: usbr-component
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish Artifacts
        id: thedeploy
        run: ./mvnw clean deploy -DMAVEN_URL_SNAPSHOTS=${{ secrets.DEPLOY_URL_SNAPSHOTS }} -DMAVEN_URL_RELEASES=${{ secrets.DEPLOY_URL_RELEASES }}
        env:
          MAVEN_USERNAME: ${{ secrets.DEPLOY_USER }}
          MAVEN_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}