name: Deploy jackson-dataformat-xlsx-lite with Maven

permissions:
  contents: read
  packages: write

# this should only be triggered manually
on: workflow_dispatch

jobs:
  publish:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: setup java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
        # these are the credentials we will need
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Artifacts
        id: thedeploy
        run: ./mvnw clean deploy